parameters:
    file_storage.local.dir: '%env(resolve:FILE_STORAGE_LOCAL_DIR)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\FileStorage\:
        resource: '../../src/FileStorage/*'

    App\FileStorage\LocalFileStorage:
        arguments:
            $storageDir: '%file_storage.local.dir%'
