services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Handler\:
        resource: '../../src/Handler/*'

    App\Handler\ShopifyStoreProcessHandler:
        arguments:
            $producer: '@old_sound_rabbit_mq.shopify_store_process_producer'

    App\Handler\ChannelAmazonProcessHandler:
        arguments:
            $producer: '@old_sound_rabbit_mq.channel_amazon_process_producer'
