parameters:
    env(PLUGINS_WEBPUSH_FILE_TITLE): 'RepuX'
    env(PLUGINS_WEBPUSH_FILE_READY_MESSAGE): 'Your data is ready for sale!'
    env(PLUGINS_WEBPUSH_FILE_EMPTY_MESSAGE): 'Your data file is empty.'
    env(PLUGINS_WEBPUSH_FILE_ERROR_MESSAGE): 'There was an error while retrieving your data.'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Notifier\:
        resource: '../../src/Notifier/*'

    App\Notifier\WebpushNotifier:
        arguments:
            $client: '@webpush.gateway_client'
