# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
          - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: false }
          - { path: '^/', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
    disable_csrf_role: ROLE_USER
    serializer:
        serialize_null: true
    view:
        view_response_listener: true
    exception:
        enabled: false
        messages:
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
