nelmio_api_doc:
    documentation:
        info:
            title: RepuX - plugins API
            version: 1.0.0
        securityDefinitions:
            auth_token:
                type: apiKey
                description: "Authentication token"
                name:  !php/const App\Security\AuthTokenAuthenticator::TOKEN_HEADER
                in: header
        security:
            - auth_token: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
