security:
    providers:
        user_provider_by_auth_token:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true
            pattern: ^/api/
            provider: user_provider_by_auth_token
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\AuthTokenAuthenticator

    access_control:
        - { path: '^/api/shopify-store/store-verify', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/api/(doc|auth)(/|$)', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/api/', roles: IS_AUTHENTICATED_FULLY }
