version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: passwd
        ports:
            - '5433:5432'

    php:
        build: docker/php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ./:/opt/repux-plugins
        links:
            - postgres
        expose:
          - 9000
        environment:
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=192.168.20.59
            PHP_IDE_CONFIG: serverName=repux-plugins

    nginx:
        build: docker/nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./:/opt/repux-plugins
            - ./docker/logs/nginx/:/var/log/nginx

    rabbitmq:
        build: docker/rabbitmq
        ports:
          - 15672:15672
