version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: passwd
        ports:
            - '5433:5432'
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - postgres
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
            - ./logs/nginx/:/var/log/nginx:cached
