parameters:
    locale: 'en'

imports:
    - { resource: services/* }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Service\:
        resource: '../src/Service/*'
        exclude: '../src/Service/{AmazonMWS,Shopify}'

    App\Form\:
        resource: '../src/Form/*'

    Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'

    App\Service\EncryptionService:
        arguments:
            $secret: '%env(ENCRYPTION_KEY)%'
